package com.swp391.evmarketplace.SWP391_Fall25_Evmarketplace.enums;

public enum ErrorCode {
    // Nhóm PROFILE
    PROFILE_FIELD_TOO_LONG,

    // Nhóm ACCOUNT
    ACCOUNT_NOT_FOUND,
    ACCOUNT_LIST_EMPTY,
    ACCOUNT_ALREADY_ACTIVE,
    ACCOUNT_ALREADY_SUSPENDED,
    ACCOUNT_BLOCKED,
    ACCOUNT_UNBLOCKED,
    ACCOUNT_CANNOT_BLOCK_DELETED,

    //phone
    PHONE_NOT_VERIFIED,
    PHONE_ALREADY_EXISTS,
    PHONE_REQUIRED,

    //update
    UPDATED_EMAIL,

    // Nhóm AVATAR
    AVATAR_FILE_REQUIRED,
    AVATAR_NOT_FOUND,

    // Nhóm SEARCH
    KEYWORD_NOT_FOUND,

    //listing
    LISTING_NOT_FOUND,

    //nhóm email
    EMAIL_ALREADY_EXISTS,
    EMAIL_FAIL,
    EMAIL_SENT,
    SEND_OTP_SUCCESSFULLY,
    SEND_OTP_FAILED,

    //OTP
    OTP_NOT_FOUND,
    INVALID_OTP,
    OTP_HAS_EXPIRED,
    OTP_ALREADY_USED,
    VERIFY_OTP_SUCCESSFULLY,

    //Token
    INVALID_TOKEN,
    TOKEN_HAS_EXPIRED,

    //branch
    BRANCH_NOT_FOUND,
    BRANCH_INACTIVE,

    //Consignment
    CONSIGNMENT_REQUEST_LIST_NOT_FOUND,
    CONSIGNMENT_REQUEST_NOT_FOUND,

    //intended
    INTENDED_FOR_REQUIRED,

    //brand
    BRAND_NOT_IN_CATEGORY,

    //model
    MODEL_NOT_FOUND,
    MODEL_NOT_BELONG_TO_CATEGORY,
    MODEL_NOT_BELONG_TO_BRAND,

    //category
    CATEGORY_NOT_FOUND;


}

