package com.swp391.evmarketplace.SWP391_Fall25_Evmarketplace.enums;

public enum ErrorCode {
    // Nhóm PROFILE
    PROFILE_FIELD_TOO_LONG,

    // Nhóm ACCOUNT
    ACCOUNT_NOT_FOUND,
    ACCOUNT_LIST_EMPTY,
    ACCOUNT_ALREADY_ACTIVE,
    ACCOUNT_ALREADY_SUSPENDED,
    ACCOUNT_BLOCKED,
    ACCOUNT_UNBLOCKED,
    ACCOUNT_CANNOT_BLOCK_DELETED,
    PHONE_NOT_VERIFIED,
    PHONE_ALREADY_EXISTS,

    //update
    UPDATED_EMAIL,

    // Nhóm AVATAR
    AVATAR_FILE_REQUIRED,
    AVATAR_NOT_FOUND,

    // Nhóm SEARCH
    KEYWORD_NOT_FOUND,

    //listing
    LISTING_NOT_FOUND;

}

